name: publish to nuget
on:
  push:
    branches:
      - master # Default release branch, may also be named 'master' or 'develop'
jobs:
  publish:
    name: build, pack & publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Setup dotnet
      #   uses: actions/setup-dotnet@v1
      #   with:
      #     dotnet-version: 3.1.200

      # Get version from tag
      - name: Get version from tag
        id: get_version
        run: echo "::set-output name=VERSION::${{ github.ref_name }}"
        env:
          GITHUB_REF_NAME: ${{ github.ref_name }}

      # Publish
      - name: publish on version change
        id: publish_nuget
        uses: brandedoutcast/publish-nuget@v2
        with:
          # Filepath of the project to be packaged, relative to root of repository
          PROJECT_FILE_PATH: Mono.Core/Mono.Core.csproj
          NUGET_KEY: ${{ secrets.NUGET_SECRET_KEY }}
          VERSION_STATIC: ${{ steps.get_version.outputs.VERSION }}