<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<PackageId>
			Mono.Core
		</PackageId>
		<Version>
			1.8.0
		</Version>
		<Authors>
			Adelowomi
		</Authors>
		<Company>
			Harmonics Technology
		</Company>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.2.5" />
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="8.0.0" />
		<PackageReference Include="Microsoft.Extensions.Options" Version="8.0.2" />
		<PackageReference Include="Refit" Version="7.2.22" />
		<None Include="../Readme.md" PackagePath="\" />
	</ItemGroup>
</Project>
